apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orders-ms
  name: orders-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orders-ms
    spec:
      containers:
        - image: southamerica-east1-docker.pkg.dev/shop-ms-482816/image-registry/orders-ms-prd
          name: orders-ms-prd
          env:
            - name: PORT
              value: "3000"
            - name: NATS_SERVER
              value: "nats://nats"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: orders-secrets
                  key: ORDERS_MS_DATABASE_URL
          resources: {}
status: {}
