apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth-ms
  name: auth-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-ms
    spec:
      containers:
        - image: southamerica-east1-docker.pkg.dev/shop-ms-482816/image-registry/auth-ms-prd
          name: auth-ms-prd
          env:
            - name: PORT
              value: "3000"
            - name: NATS_SERVER
              value: "nats://nats"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: AUTH_MS_DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: JWT_SECRET
          resources: {}
status: {}
